spring:
  application:
    name: eureka-demo
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false # 此客户端是否获取eureka服务器注册表上的注册信息 默认true
  server:
    enable-self-preservation: false # 关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 # 扫描失效服务的间隔时间 默认60秒

# --spring.profiles.active=peer1
---
spring:
  application:
    name: eureka-demo
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 4000 # 扫描失效服务的间隔时间 默认60秒
    peer-eureka-nodes-update-interval-ms: 30000 # eureka节点间间隔多长时间更新一次数据 默认10分钟
# --spring.profiles.active=peer2
---
spring:
  application:
    name: eureka-demo
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 4000 # 扫描失效服务的间隔时间 默认60秒
    peer-eureka-nodes-update-interval-ms: 30000 # eureka节点间间隔多长时间更新一次数据 默认10分钟
